# Generated by Django 4.2.6 on 2024-01-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
            preserve_default=False,
        ),
    ]
