# Generated by Django 4.2.6 on 2024-01-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
