# Generated by Django 4.2.6 on 2024-01-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
