# Generated by Django 4.2.6 on 2024-01-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_attendance_attendance_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Time',
            field=models.TimeField(default='12:10'),
            preserve_default=False,
        ),
    ]
