# Generated by Django 4.0.1 on 2024-01-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sem',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
